* Summary
:PROPERTIES:
:CUSTOM_ID: summary
:END:

#+BEGIN_HTML
<a href="https://www.mondragon.edu/en/research-transfer/engineering-technology/research-and-transfer-groups/-/mu-inv-mapping/ikertzaile/inaki-garitano-garitano" target="_blank" title="I침aki Garitano">I침aki Garitano</a> is a researcher/lecturer in Electronics and Computer Engineering department and <a href="https://www.mondragon.edu/en/research-transfer/engineering-technology/research-and-transfer-groups/-/mu-inv-mapping/group/data-analysis-and-cybersecurity" target="_blank" title="Data Analysis and cybersecurity group">Data Analysis and Cybersecurity</a> group of <a href="http://www.mondragon.edu/en/" target="_blank" title="Mondragon Unibertsitatea">Mondragon Unibertsitatea</a>, Mondragon University.
He holds a PhD titled <a href="https://www.mondragon.edu/en/phd/defended-theses/-/tesis/2013-2014/i%C3%B1aki-garitano-garitano" target="_blank" title="Behavioral Modeling for Anomaly Detection in Industrial Control Systems"><i>Behavioral Modeling for Anomaly Detection in Industrial Control Systems</i></a>, and MSc in Telecommunication Engineering, both from <a href="http://www.mondragon.edu/en/" target="_blank" title="Mondragon Unibertsitatea">Mondragon Unibertsitatea</a>. 
Before joining <a href="http://www.mondragon.edu/en/" target="_blank" title="Mondragon Unibertsitatea">Mondragon Unibertsitatea</a> in 2015, he worked in <a href="http://www.mn.uio.no/its/english/" target="_blank" title="Universitetssenteret p친 Kjeller (UNIK)">Universitetssenteret p친 Kjeller (UNIK)</a> as postdoctoral researcher. 
In addition, he is the CTO of the <a href="http://www.basicinternet.org/" target="_blank" title="Basic Internet Foundation">Basic Internet Foundation</a>. His interests include Data Science, Security, Privacy, Industrial Automation and Control Systems and Information and Communication Networks including Internet of Things. 
He currently participates in several European, national and regional level public funding projects.
#+END_HTML

Specialties: Data Analysis, Anomaly Detection Systems, Intrusion Detection Systems, ICS Security, Critical Information Infrastructure Protection, SCADA Security, Computer and Network Security.

