* Summary
:PROPERTIES:
:CUSTOM_ID: summary
:END:

#+BEGIN_HTML
Iñaki Garitano is a researcher/lecturer in Electronics and Computer Engineering department and <a href="http://www.mondragon.edu/en/phs/research/research-teams/telematics" target="_blank" title="Telematics research team">Telematics</a> team of <a href="http://www.mondragon.edu/en/" target="_blank" title="Mondragon Unibertsitatea">Mondragon Unibertsitatea</a>, Mondragon University. 
He holds a <a href="http://www.mondragon.edu/es/eps/actualidad/noticias/lectura-de-la-tesis-de-inaki-garitano" target="_blank" title="PhD">PhD</a> titled /Behavioral Modeling for Anomaly Detection in Industrial Control Systems/, and MSc in Telecommunication Engineering, both from <a href="http://www.mondragon.edu/en/" target="_blank" title="Mondragon Unibertsitatea">Mondragon Unibertsitatea</a>. 
Before joining <a href="http://www.mondragon.edu/en/" target="_blank" title="Mondragon Unibertsitatea">Mondragon Unibertsitatea</a> in 2015, he worked in <a href="http://www.unik.no/" target="_blank" title="Universitetssenteret på Kjeller (UNIK)">Universitetssenteret på Kjeller (UNIK)</a> as postdoctoral researcher. 
In addition, he is the CTO of the <a href="http://www.basicinternet.org/" target="_blank" title="Basic Internet Foundation">Basic Internet Foundation</a>. His interests include Data Science, Security, Privacy, Industrial Automation and Control Systems and Information and Communication Networks including Internet of Things. 
He currently participates in several European, national and regional level public funding projects including MANTIS [ECSEL-2014-1 662189], MC-SUITE [H2020-FoF-2015 680478], SERVROLL [EXP-00088623/CIIP-20161009], BID3ABI [KK-2016/00096], EDAR 4.0 [ZE-2016/00020], HEALSYSII [ 2016222007 ], etc. where he is responsible of several tasks including data analysis, security, scalability, HPC, among others.
#+END_HTML

Specialties: Data Analysis, Anomaly Detection Systems, Intrusion Detection Systems, ICS Security, Critical Information Infrastructure Protection, SCADA Security, Computer and Network Security.
